### PR TITLE
Moyodaniel week 1&2

### PR DESCRIPTION
**Pull request by MoyoDaniel**
THIS IS A PULL REQUEST TEMPLATE! This helps you complete a pull request. Please follow the instructions below. 

## Description
Tell us about your pull request!

**Please make sure your submission is in the correct directory**. In most cases, this is in submissions/YOUR-GITHUB-USERNAME/Week-Number/filename.

For example, if @codedentwickler is completing Week 1:
- I solved the Week 1 task.
- I create a new file inside submissions/codedentwickler/Week1/
- I name this file fizzbuzz.py, hence we have the fizzbuzz solution in submissions/codedentwickler/Week1/fizzbuzz.py

### CODE REVIEW

**Comment by MoyoDaniel** [comment]
My pull request for week 1&2

**Comment by tegaphilip** [comment]
@MoyoDaniel great job. Can you do one more thing though? Format the `Fizzbuzz.cpp` code so that it is indented properly. Then we can merge this pull request.

**Review by codedentwickler — APPROVED** [review]
Great Job.

**Comment by codedentwickler** [comment]
@tegaphilip Moyo updated the PR with the changes you proposed. Merging this now.

**Comment by tegaphilip** [comment]
@MoyoDaniel Nice. @codedentwickler thanks.

**Pull request merged**
